name: weather_app
description: A new Flutter project.
publish_to: "none"
version: 1.0.0+1

environment:
  sdk: ">=3.1.0 <4.0.0"

dependencies:
  auto_route: ^7.8.4
  cupertino_icons: ^1.0.2
  figma_squircle: ^0.5.3
  flutter:
    sdk: flutter
  flutter_animate: ^4.2.0+1
  google_fonts: ^6.1.0
  intl: ^0.18.1
  weather_repository:
    path: packages/weather_repository

dev_dependencies:
  auto_route_generator: ^7.3.2
  build_runner: ^2.4.6
  flutter_test:
    sdk: flutter
  flutter_lints: ^2.0.0

flutter:
  uses-material-design: true
