name: weather_app
description: A Flutter app to retrieve the weather forecasts in a number of UK cities.
publish_to: "none"
version: 1.0.0+1

environment:
  sdk: ">=3.1.0 <4.0.0"

dependencies:
  auto_route: ^7.8.4
  bloc: ^8.1.2
  collection: ^1.17.2
  cupertino_icons: ^1.0.2
  easy_localization: ^3.0.3
  equatable: ^2.0.5
  figma_squircle: ^0.5.3
  flutter:
    sdk: flutter
  flutter_animate: ^4.2.0+1
  flutter_bloc: ^8.1.3
  flutter_dotenv: ^5.1.0
  get_it: ^7.6.4
  google_fonts: ^6.1.0
  http_service:
    path: packages/http_service
  intl: ^0.18.1
  logger_service:
    path: packages/logger_service
  shared_preferences: ^2.2.2
  weather_repository:
    path: packages/weather_repository

dev_dependencies:
  auto_route_generator: ^7.3.2
  bloc_test: ^9.1.5
  build_runner: ^2.4.6
  flutter_test:
    sdk: flutter
  flutter_lints: ^2.0.0
  mocktail: ^1.0.1

flutter:
  uses-material-design: true
  assets:
      - assets/images/
      - assets/translations/
      - assets/env/