name: logger_service
description: A Dart package to log data to console.
version: 1.0.0
publish_to: none

environment:
  sdk: ^3.1.0

dependencies:
  dev: ^1.0.0
  logger: ^2.0.2+1

dev_dependencies:
  lints: ^2.0.0
  mocktail: ^1.0.1
  test: ^1.21.0
