name: http_service
description: A Dart package to interact with data on the web.
version: 1.0.0
publish_to: none

environment:
  sdk: ^3.1.0

dependencies:
  dev: ^1.0.0
  http: ^1.1.0
  logger_service:
    path: ../logger_service

dev_dependencies:
  mocktail: ^1.0.1
  lints: ^2.0.0
  test: ^1.21.0
